config/routes.rb
Rails.application.routes.draw do
  resources :categories, defaults: { format: :json }

  resources :plugins, defaults: { format: :json }

  get 'categories/:id/search', controller: 'categories', to: :search_plugins

  ['plugin_images', 'plugin_files'].each do |ctrl|
    get "#{ctrl}/upload", controller: "#{ctrl}", to: :post_chunk!
    post "#{ctrl}/upload", controller: "#{ctrl}", to: :post_chunk!
    get "#{ctrl}/status", controller: "#{ctrl}", to: :options
    match "#{ctrl}/upload", :controller => "#{ctrl}", :action => 'options', :constraints => {:method => 'OPTIONS'}, :via => [:options]
  end

end

app/models/plugin.rb
class Plugin < ActiveRecord::Base
	belongs_to :category, counter_cache: true
  has_many :plugin_images, :dependent => :destroy
  has_many :plugin_files, :dependent => :destroy
	has_many :plugin_links, :dependent => :destroy
	
	validates :name, length: { maximum: 140 }, presence: true
	validates :version, length: { maximum: 10 }
	validates :author, presence: true
	validates :description, presence: true
end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  before_action :set_plugin, only: [:show, :edit, :update, :destroy]

  # GET /plugins
  # GET /plugins.json
  def index
    if params[:name].present?
      @plugins = Plugin.where('name like ?', "%#{params[:name]}%")
    else
      @plugins = Plugin.order('created_at').limit(5)
    end
  end

  # GET /plugins/1
  # GET /plugins/1.json
  def show
  end

  # GET /plugins/new
  def new
    @plugin = Plugin.new
  end

  # GET /plugins/1/edit
  def edit
  end

  # POST /plugins
  # POST /plugins.json
  def create
    @plugin = Plugin.new(plugin_params)

    respond_to do |format|
      if @plugin.save
        format.html { redirect_to @plugin, notice: 'Plugin was successfully created.' }
        format.json { render :show, status: :created, location: @plugin }
      else
        format.html { render :new }
        format.json { render json: @plugin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plugins/1
  # PATCH/PUT /plugins/1.json
  def update
    respond_to do |format|
      if @plugin.update(params.require(:plugin).permit(:name, :version, :author, :category_id, :description))
        if params[:new_images].present?
          for image_obj in params.require(:new_images) do
            @plugin.plugin_images.new(image_obj.permit(:url)).save
          end
          # @plugin.plugin_images.build(params.require(:new_images))
        end
        if params[:new_files].present?
          for file_obj in params.require(:new_files) do
            @plugin.plugin_files.new(file_obj.permit(:path, :name, :size)).save
          end
          # @plugin.file_obj.build(params.require(:new_files))
        end
        if params[:new_links].present?
          for link_obj in params.require(:new_links) do
            @plugin.plugin_links.new(link_obj.permit(:name, :url)).save
          end
          # @plugin.file_obj.build(params.require(:new_files))
        end
        if params[:removed_images].present?
          @plugin.plugin_images.where(:id => params[:removed_images]).destroy_all
        end
        if params[:removed_files].present?
          @plugin.plugin_files.where(:id => params[:removed_files]).destroy_all
        end
        format.html { redirect_to @plugin, notice: 'Plugin was successfully updated.' }
        format.json { render :show, status: :ok, location: @plugin }
      else
        format.html { render :edit }
        format.json { render json: @plugin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plugins/1
  # DELETE /plugins/1.json
  def destroy
    @plugin.destroy
    respond_to do |format|
      format.html { redirect_to plugins_url, notice: 'Plugin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plugin
      @plugin = Plugin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plugin_params
      params.require(:plugin).permit(:name, :author, :description, :version)
    end
end

app/helpers/plugins_helper.rb
module PluginsHelper
end

app/views/plugins/_form.html.erb
<%= form_for(@plugin) do |f| %>
  <% if @plugin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plugin.errors.count, "error") %> prohibited this plugin from being saved:</h2>

      <ul>
      <% @plugin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plugins/edit.html.erb
<h1>Editing plugin</h1>

<%= render 'form' %>

<%= link_to 'Show', @plugin %> |
<%= link_to 'Back', plugins_path %>

app/views/plugins/index.html.erb
<h1>Listing plugins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Description</th>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plugins.each do |plugin| %>
      <tr>
        <td><%= plugin.name %></td>
        <td><%= plugin.author %></td>
        <td><%= plugin.description %></td>
        <td><%= plugin.version %></td>
        <td><%= link_to 'Show', plugin %></td>
        <td><%= link_to 'Edit', edit_plugin_path(plugin) %></td>
        <td><%= link_to 'Destroy', plugin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plugin', new_plugin_path %>

app/views/plugins/new.html.erb
<h1>New plugin</h1>

<%= render 'form' %>

<%= link_to 'Back', plugins_path %>

app/views/plugins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plugin.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @plugin.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plugin.description %>
</p>

<p>
  <strong>Version:</strong>
  <%= @plugin.version %>
</p>

<%= link_to 'Edit', edit_plugin_path(@plugin) %> |
<%= link_to 'Back', plugins_path %>